# The name of our workflow
name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      OPENFST_TAG: 1.8.1-android
      THRAX_TAG: 1.3.6-android
      FLITE_TAG: v2.3-pre1-android
      NDK_VER: 23.1.7779620
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Get CMake
        uses: lukka/get-cmake@v3.20.1
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VER}" --sdk_root=${ANDROID_SDK_ROOT}
      - name: Setup NDK
        run: |
          echo "ANDROID_NDK=$ANDROID_HOME/ndk/${NDK_VER}" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/${NDK_VER}" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_HOME/ndk/${NDK_VER}" >> $GITHUB_ENV
      - name: "Check build env"
        run: |
          pwd
          ls -al
          echo "ANDROID_HOME:"
          ls -al $ANDROID_HOME/
      - name: "Create local.properties"
        run: |
          echo "flite.dir=`pwd`/3rdparty/ndk">local.properties
          echo "3rdparty.dir=`pwd`/3rdparty/ndk" >>local.properties
      - name: Cache native libs
        uses: actions/cache@v2
        env:
          cache-name: cache-native-libs
        with:
          # cache key is unique to the combination of all native lib tags
          path: 3rdparty/
          key: ${{ env.OPENFST_TAG }}_${{ env.THRAX_TAG }}_${{ env.FLITE_TAG }}_dl_${{ env.cache-name }}

      - name: "Download & extract native libs"
        run: .github/scripts/dl_3rdparty.sh
        shell: bash
      - name: "Build the app"
        run: ./gradlew build
      - name: Archive reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: archive-reports
          path: |
            app/build/reports/**/*
